name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Display Python version
      run: python --version
    
    - name: Run tests with unittest
      run: |
        python -m unittest discover tests -v
    
    - name: Verify demo runs
      run: |
        python demo.py
    
    - name: Verify imports work
      run: |
        python -c "from src.services.alert_service import AlertService; print('Import test passed')"
